import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
// import 'bootstrap/dist/js/bootstrap.bundle.min';
import Navbar from "@/components/navbar";
import Head from 'next/head';
import Footer from "@/components/footer";
import Link from "next/link";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Foodies Corner",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Basic */}
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />

        {/* Mobile Metas */}
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

        {/* Site Metas */}
        <meta name="keywords" content="" />
        <meta name="description" content="" />
        <meta name="author" content="" />


        {/* Owl Carousel CSS */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" /> */}

        {/* Nice Select CSS */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" /> */}

        {/* Font Awesome CSS */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" /> */}

  

      </Head>
      <body>
        <div>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </div>
        <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        strategy="afterInteractive" // Ensures the script runs after the page is interactive
      />
      
        {/* <!-- isotope js --> */}
        {/* <Script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></Script> */}
        {/* <!-- nice select --> */}
        {/* <Script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></Script> */}
        {/* <!-- custom js --> */}
       
        {/* <!-- Google Map --> */}
        <Script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
        </Script>
        {/* <!-- End Google Map --> */}
      </body>
    </html>
  );
}
