paytm.payment:
    sandbox:
      merchantId: "StYCNx46214940700947"
      merchantKey: "aveI6SQ3bY3OtviW"
      website: "WEBSTAGING"
      channelId: "WEB"
      Industry Type: Retail
      paytmUrl: 
      callbackUrl: 
      detail:
      MID: ${paytem.payment.sandbox.merchantid}
      CHANNEL_ID: ${paytem.payment.sandbox.channelid}
      INDUSTRY_TYPE_ID: ${paytem.payment.sandbox.Industrytypeid}
      WEBSITE: ${paytem.payment.sandbox.website}
      CALLBACK_URL: ${paytem.payment.sandbox.callbackUrl}